### ISSUE TITLE
Add a docker-compose file for all of the examples

### ISSUE THREAD

**Issue by dianvaltodorov** [elastic/examples#233]
Docker compose would provide an easy and fast way to run any of the example.

As of now if someone wants to run any of the examples in this repository, he needs to install a lot of additional requirements on his machine(say php or java or whatever else is necessary). If everything is dockerized then running the example would consist only of a single `docker-compose up` command.

**Comment by RooieRakkert** [comment]
I faced this same issue. 

You can save this file as `docker-compose.yaml` and run with `docker-compose up`:
```
version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.10
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.10
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.9
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    ports:
      - 5601:5601
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
```

`docker-compose down` will bring the docker network down, `docker-compose down -v` will bring it down and destroy your local data too.
Please note that this file runs outdated ES/Kibana versions, as most `ingest-data.sh` files from the examples do not work with version 6+.
